services:
  s-service:
    build:
      context: .
    image: thaimy1614/s-service:latest
    env_file:
      - ./.env/docker.env
    ports:
      - 8080:8080

  s-service-db:
    image: postgres:16.3
    restart: always
    user: postgres
    env_file:
      - path: ./.env/docker.env
    volumes:
      - s-service-data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #Redis#
  s-service-redis:
    image: docker.io/redis:7.2.3
    container_name: s-service-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - s-redis-data:/data

volumes:
  s-service-data:
  s-redis-data:


