spring:
  application:
    name: s-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: ${SPRING_MAIL_PORT:587}
    protocol: ${SPRING_MAIL_PROTOCOL:smtp}
    test-connection: ${SPRING_MAIL_TEST_CONNECTION:false}
    properties:
      mail.smtp.ssl.trust: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST:*}
      mail.smtp.auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
      mail.smtp.starttls.enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
  sql:
    init:
      encoding: UTF-8

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}

jwt:
  signer-key: ${JWT_SIGNING_KEY}
  expiration-duration: 36000 # in sec
  refreshable-duration: 36000 # in sec

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

application:
  api:
    prefix: /api
    url: ${API_URL}
  frontend:
    url: ${FRONT_END_PREFIX}